### ISSUE TITLE
todo-week 2022-09-20

### ISSUE THREAD

**Issue by pwang1997** [GEET-Telfer/assessment#2]
- [x] under discussion: score formula
- [ ] editable assessment questions
- [x] add hasNA attribute
- [x] reflect assessment questions on user interface
- [x] email service: after user submits an assessment, send a summary email to user email inbox if applicable
- [x] backend validation

**Comment by pwang1997** [comment]
Move undone work to next week todo list
